-- MySQL Script generated by MySQL Workbench
-- Sat Feb 26 15:42:01 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pizzeria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pizzeria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pizzeria` DEFAULT CHARACTER SET utf8 ;
USE `pizzeria` ;

-- -----------------------------------------------------
-- Table `pizzeria`.`board`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`board` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`dough_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`dough_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`ingredient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`ingredient` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`pizza_size`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`pizza_size` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `size_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`pizza` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` DOUBLE NOT NULL,
  `image` MEDIUMTEXT NOT NULL,
  `visibility` TINYINT(4) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`board_has_pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`board_has_pizza` (
  `board_id` INT NOT NULL,
  `pizza_id` INT NOT NULL,
  PRIMARY KEY (`board_id`, `pizza_id`),
  INDEX `fk_board_has_pizza_pizza1_idx` (`pizza_id` ASC) VISIBLE,
  INDEX `fk_board_has_pizza_board_idx` (`board_id` ASC) VISIBLE,
  CONSTRAINT `fk_board_has_pizza_board`
    FOREIGN KEY (`board_id`)
    REFERENCES `pizzeria`.`board` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_board_has_pizza_pizza1`
    FOREIGN KEY (`pizza_id`)
    REFERENCES `pizzeria`.`pizza` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`dough_type_has_pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`dough_type_has_pizza` (
  `dough_type_id` INT NOT NULL,
  `pizza_id` INT NOT NULL,
  PRIMARY KEY (`dough_type_id`, `pizza_id`),
  INDEX `fk_dough_type_has_pizza_pizza1_idx` (`pizza_id` ASC) VISIBLE,
  INDEX `fk_dough_type_has_pizza_dough_type1_idx` (`dough_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_dough_type_has_pizza_dough_type1`
    FOREIGN KEY (`dough_type_id`)
    REFERENCES `pizzeria`.`dough_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dough_type_has_pizza_pizza1`
    FOREIGN KEY (`pizza_id`)
    REFERENCES `pizzeria`.`pizza` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`ingredient_has_pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`ingredient_has_pizza` (
  `ingredient_id` INT NOT NULL,
  `pizza_id` INT NOT NULL,
  PRIMARY KEY (`ingredient_id`, `pizza_id`),
  INDEX `fk_ingredient_has_pizza_pizza1_idx` (`pizza_id` ASC) VISIBLE,
  INDEX `fk_ingredient_has_pizza_ingredient1_idx` (`ingredient_id` ASC) VISIBLE,
  CONSTRAINT `fk_ingredient_has_pizza_ingredient1`
    FOREIGN KEY (`ingredient_id`)
    REFERENCES `pizzeria`.`ingredient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ingredient_has_pizza_pizza1`
    FOREIGN KEY (`pizza_id`)
    REFERENCES `pizzeria`.`pizza` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`pizza_size_has_pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`pizza_size_has_pizza` (
  `pizza_size_id` INT NOT NULL,
  `pizza_id` INT NOT NULL,
  PRIMARY KEY (`pizza_size_id`, `pizza_id`),
  INDEX `fk_pizza_size_has_pizza_pizza1_idx` (`pizza_id` ASC) VISIBLE,
  INDEX `fk_pizza_size_has_pizza_pizza_size1_idx` (`pizza_size_id` ASC) VISIBLE,
  CONSTRAINT `fk_pizza_size_has_pizza_pizza_size1`
    FOREIGN KEY (`pizza_size_id`)
    REFERENCES `pizzeria`.`pizza_size` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pizza_size_has_pizza_pizza1`
    FOREIGN KEY (`pizza_id`)
    REFERENCES `pizzeria`.`pizza` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`user_addres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`user_addres` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `country` MEDIUMTEXT NOT NULL,
  `city` MEDIUMTEXT NOT NULL,
  `street_name` VARCHAR(45) NOT NULL,
  `house_number` INT NOT NULL,
  `frame` VARCHAR(45) NOT NULL,
  `enterance_number` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`payment_method`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`payment_method` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`delivery_time`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`delivery_time` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `time` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(145) NOT NULL,
  `last_name` VARCHAR(145) NOT NULL,
  `user_name` MEDIUMTEXT NOT NULL,
  `phone_number` CHAR(13) NOT NULL,
  `is_banned` TINYINT(4) NOT NULL,
  `user_addres_id` INT NOT NULL,
  PRIMARY KEY (`iduser`, `user_addres_id`),
  UNIQUE INDEX `iduser_UNIQUE` (`iduser` ASC) VISIBLE,
  INDEX `fk_user_user_addres1_idx` (`user_addres_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_user_addres1`
    FOREIGN KEY (`user_addres_id`)
    REFERENCES `pizzeria`.`user_addres` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`order` (
  `pizza_id` INT NOT NULL,
  `user_iduser` INT NOT NULL,
  `payment_method_id` INT NOT NULL,
  `delivery_time_id` INT NOT NULL,
  PRIMARY KEY (`pizza_id`, `user_iduser`, `payment_method_id`, `delivery_time_id`),
  INDEX `fk_pizza_has_user_user1_idx` (`user_iduser` ASC) VISIBLE,
  INDEX `fk_pizza_has_user_pizza1_idx` (`pizza_id` ASC) VISIBLE,
  INDEX `fk_order_payment_method1_idx` (`payment_method_id` ASC) VISIBLE,
  INDEX `fk_order_delivery_time1_idx` (`delivery_time_id` ASC) VISIBLE,
  CONSTRAINT `fk_pizza_has_user_pizza1`
    FOREIGN KEY (`pizza_id`)
    REFERENCES `pizzeria`.`pizza` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pizza_has_user_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `pizzeria`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_payment_method1`
    FOREIGN KEY (`payment_method_id`)
    REFERENCES `pizzeria`.`payment_method` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_delivery_time1`
    FOREIGN KEY (`delivery_time_id`)
    REFERENCES `pizzeria`.`delivery_time` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
